---
apiVersion: elasticache.aws.m.upbound.io/v1beta1
kind: ReplicationGroup
metadata:
  name: "{{ .Values.innerHelm.releaseName }}-{{ .Values.envName }}"
  annotations:
    crossplane.io/external-name: "{{ .Values.innerHelm.releaseName }}-{{ .Values.envName }}"
spec:
  managementPolicies: ["*"]
  forProvider:
    description: Valkey Cluster for Airflow Celery Workers
    region: "{{ .Values.aws.region }}"
    nodeType: cache.t4g.micro
    kmsKeyId: "{{ .Values.aws.kmsKeyId }}"
    engine: valkey
    engineVersion: "{{ .Values.aws.elasticache.engineVersion }}"
    securityGroupIds:
      - "{{ .Values.aws.elasticache.securityGroupID }}"
    subnetGroupName: "{{ .Values.aws.elasticache.cacheSubnetGroupName }}"
    automaticFailoverEnabled: {{ .Values.aws.elasticache.automaticFailoverEnabled }}
    multiAzEnabled: {{ .Values.aws.elasticache.multiAZEnabled }}
    numNodeGroups: {{ .Values.aws.elasticache.numNodeGroups }}
    replicasPerNodeGroup: {{ .Values.aws.elasticache.replicasPerNodeGroup }}
    transitEncryptionEnabled: true
    atRestEncryptionEnabled: "true"
    autoMinorVersionUpgrade: "true"
    authTokenSecretRef:
      name: airflow-valkey-creds
      key: password

  # Crossplane natively replaces ACK's FieldExport.
  # This automatically extracts the endpoint, username, etc., into a Kubernetes Secret.
  writeConnectionSecretToRef:
    name: crossplane-{{ .Release.Name }}-valkey
