---
apiVersion: iam.services.k8s.aws/v1alpha1
kind: Policy
metadata:
  name: {{ .Release.Name }}-s3
  # annotations:
  #   services.k8s.aws/adoption-policy: "adopt-or-create"
  #   services.k8s.aws/adoption-fields: |
  #     {"arn": "arn:aws:iam::958289163165:policy/{{ .clusterName }}-airflow-s3"}
spec:
  name: {{ .clusterName }}-{{ .Release.Name }}-s3
  policyDocument: |
    {
      "Statement": [
          {
              "Action": [
                  "s3:DeleteObject",
                  "s3:GetObject",
                  "s3:ListBucket",
                  "s3:PutObject",
                  "s3:HeadObject"
              ],
              "Effect": "Allow",
              "Resource": [
                  "arn:aws:s3:::phl-{{ .Release.Name }}-xcom-{{ .clusterName }}",
                  "arn:aws:s3:::phl-{{ .Release.Name }}-xcom-{{ .clusterName }}/*",
                  "arn:aws:s3:::phl-{{ .Release.Name }}-logs-{{ .clusterName }}",
                  "arn:aws:s3:::phl-{{ .Release.Name }}-logs-{{ .clusterName }}/*",
                  "arn:aws:s3:::citygeo-airflow-databridge2",
                  "arn:aws:s3:::citygeo-airflow-databridge2/*",
                  "arn:aws:s3:::citygeo-airflow-databridge2-testing",
                  "arn:aws:s3:::citygeo-airflow-databridge2-testing/*",
                  "arn:aws:s3:::citygeo-dbt-artifacts-testing/*",
                  "arn:aws:s3:::citygeo-dbt-artifacts-testing",
                  "arn:aws:s3:::citygeo-dbt-artifacts/*",
                  "arn:aws:s3:::citygeo-dbt-artifacts",
                  "arn:aws:s3:::opendata-downloads",
                  "arn:aws:s3:::opendata-downloads/*",
                  "arn:aws:s3:::databridge-glacier",
                  "arn:aws:s3:::databridge-glacier/*",
                  "arn:aws:s3:::oit-server-inventory/*",
                  "arn:aws:s3:::oit-server-inventory"
              ]
          }
      ],
      "Version": "2012-10-17"
    }
---
apiVersion: iam.services.k8s.aws/v1alpha1
kind: Role
metadata:
  name: {{ .Release.Name }}-irsa
  # annotations:
  #   services.k8s.aws/adoption-policy: "adopt-or-create"
  #   services.k8s.aws/adoption-fields: |
  #     {"name": "{{ .clusterName }}-airflow-irsa"}
spec:
  name: {{ .clusterName }}-{{ .Release.Name }}-irsa
  description: Airflow IRSA
  assumeRolePolicyDocument: |
    {
      "Version": "2012-10-17",
      "Statement": [
          {
              "Sid": "AllowClusterToAssume",
              "Effect": "Allow",
              "Principal": {
                  "Federated": "{{ .aws.clusterOIDCArn }}"
              },
              "Action": "sts:AssumeRoleWithWebIdentity",
              "Condition": {
                  "StringLike": {
                      "{{ .aws.clusterOIDCUrl }}:sub": "system:serviceaccount:{{ .Release.Namespace }}:*"
                  }
              }
          }
      ]
    }
  policies:
    - "{{ .aws.kmsPolicyArn }}"
    - "arn:aws:iam::958289163165:policy/{{ .clusterName }}-{{ .Release.Name }}-s3"
  #policyRefs:
  #  - from:
  #      name: airflow
