---
apiVersion: citygeo.phila.city/v1alpha1
kind: XPrivateS3Bucket
metadata:
  name: phl-{{ .Values.innerHelm.releaseName }}-logs-{{ .Values.clusterName }}
spec:
  managementPolicies:
    {{- toYaml .Values.aws.s3.managementPolicies | nindent 4 }}
  forceDestroy: {{ .Values.aws.s3.forceDelete }}
---
apiVersion: citygeo.phila.city/v1alpha1
kind: XPrivateS3Bucket
metadata:
  name: phl-{{ .Values.innerHelm.releaseName }}-xcom-{{ .Values.clusterName }}
spec:
  managementPolicies:
    {{- toYaml .Values.aws.s3.managementPolicies | nindent 4 }}
  forceDestroy: {{ .Values.aws.s3.forceDelete }}
