---
apiVersion: elasticache.services.k8s.aws/v1alpha1
kind: ReplicationGroup
metadata:
  name: {{ .Release.Name }}-valkey
  # annotations:
  #   services.k8s.aws/adoption-policy: "adopt-or-create"
  #   services.k8s.aws/adoption-fields: |
  #     {"replicationGroupID": "{{ .name }}-{{ .envName }}"}
spec:
  replicationGroupID: "{{ .Release.Name }}-{{ .envName }}"
  description: Valkey Cluster for Airflow Celery Workers
  cacheNodeType: cache.t4g.micro
  kmsKeyID: "${kms_id}"
  engine: valkey
  engineVersion: "9.0"
  securityGroupIDs:
    - "${elasticache_sg_id}"
  cacheSubnetGroupName: "${elasticache_subnet_group}"
  transitEncryptionEnabled: true
  atRestEncryptionEnabled: true
  authToken:
    name: airflow-valkey-creds
    key: password
---
apiVersion: services.k8s.aws/v1alpha1
kind: FieldExport
metadata:
  name: {{ .Release.Name }}-valkey
spec:
  from:
    path: ".status.nodeGroups[0].primaryEndpoint"
    resource:
      group: rds.services.k8s.aws
      kind: DBInstance
      name: openmetadata-postgres
  to:
    name: ack-outputs
    namespace: flux-system
    kind: secret
