---
apiVersion: citygeo.phila.city/v1alpha1
kind: IRSA
metadata:
  name: "{{ .Values.clusterName }}-{{ .Values.innerHelm.releaseName }}-irsa"
spec:
  managementPolicies:
    {{- toYaml .Values.aws.iam.managementPolicies | nindent 4 }}
  import: {{ .Values.aws.iam.import }}
  serviceAccount:
    create: true
    name: "{{ .Values.innerHelm.releaseName }}-irsa"
  forProvider:
    forceDetachPolicies: {{ .Values.aws.iam.forceDetachPolicies }} 
    policyARNsToAttach:
      - "{{ .Values.aws.kmsPolicyArn }}"
    policyJSON: |
      {
        "Statement": [
            {
                "Action": [
                    "s3:DeleteObject",
                    "s3:GetObject",
                    "s3:ListBucket",
                    "s3:PutObject",
                    "s3:HeadObject"
                ],
                "Effect": "Allow",
                "Resource": [
                    "arn:aws:s3:::phl-{{ .Values.innerHelm.releaseName }}-xcom-{{ .Values.clusterName }}",
                    "arn:aws:s3:::phl-{{ .Values.innerHelm.releaseName }}-xcom-{{ .Values.clusterName }}/*",
                    "arn:aws:s3:::phl-{{ .Values.innerHelm.releaseName }}-logs-{{ .Values.clusterName }}",
                    "arn:aws:s3:::phl-{{ .Values.innerHelm.releaseName }}-logs-{{ .Values.clusterName }}/*",
                    "arn:aws:s3:::citygeo-airflow-databridge2",
                    "arn:aws:s3:::citygeo-airflow-databridge2/*",
                    "arn:aws:s3:::citygeo-airflow-databridge2-testing",
                    "arn:aws:s3:::citygeo-airflow-databridge2-testing/*",
                    "arn:aws:s3:::citygeo-dbt-artifacts-testing/*",
                    "arn:aws:s3:::citygeo-dbt-artifacts-testing",
                    "arn:aws:s3:::citygeo-dbt-artifacts/*",
                    "arn:aws:s3:::citygeo-dbt-artifacts",
                    "arn:aws:s3:::opendata-downloads",
                    "arn:aws:s3:::opendata-downloads/*",
                    "arn:aws:s3:::databridge-glacier",
                    "arn:aws:s3:::databridge-glacier/*",
                    "arn:aws:s3:::oit-server-inventory/*",
                    "arn:aws:s3:::oit-server-inventory"
                ]
            }
        ],
        "Version": "2012-10-17"
      }
