---
apiVersion: elasticache.services.k8s.aws/v1alpha1
kind: ReplicationGroup
metadata:
  name: {{ .Release.Name }}-valkey
  # annotations:
  #   services.k8s.aws/adoption-policy: "adopt-or-create"
  #   services.k8s.aws/adoption-fields: |
  #     {"replicationGroupID": "{{ .name }}-${env_name}"}
spec:
  replicationGroupID: "{{ .Release.Name }}-${env_name}"
  description: Valkey Cluster for Airflow Celery Workers
  cacheNodeType: cache.t4g.micro
  kmsKeyID: "${kms_id}"
  engine: valkey
  engineVersion: "9.0"
  securityGroupIDs:
    - "${elasticache_sg_id}"
  cacheSubnetGroupName: "${elasticache_subnet_group}"
  transitEncryptionEnabled: true
  atRestEncryptionEnabled: true
  authToken:
    name: airflow-valkey
    key: password
