apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.innerHelm.releaseName }}-venvs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 15Gi
