---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-pgbouncer-config
spec:
  refreshInterval: 24h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: keeper
  target:
    name: {{ .Release.Name }}-pgbouncer-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        pgbouncer.ini: |
          [databases]
          postgres = host={{ .db_host }} dbname=postgres port=5432
          [pgbouncer]
          pool_mode = transaction
          listen_port = 6543
          listen_addr = *
          # https://www.pgbouncer.org/config.html
          default_pool_size = 130
          auth_type = scram-sha-256
          auth_file = /etc/pgbouncer/users.txt
          stats_users = postgres
          ignore_startup_parameters = extra_float_digits
          server_tls_sslmode = prefer
        users.txt: |
          "postgres" "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.secrets.dbPasswordSecretName }}
        property: password
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: {{ .Values.secrets.k8sSecretStore }}
    - secretKey: db_host
      remoteRef:
        key: ack-outputs
        property: {{ .Release.Namespace }}.{{ .Release.Name }}-rds-host
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: {{ .Values.secrets.k8sSecretStore }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-db
spec:
  # How often the Keeper API is hit
  refreshInterval: 24h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: keeper
  target:
    name: {{ .Release.Name }}-db # Name of the k8s Secret to be created
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        connection: "postgresql://postgres:{{ .password }}@airflow-pgbouncer.airflow:6543/postgres"
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.secrets.dbPasswordSecretName }}
        property: password
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: {{ .Values.secrets.k8sSecretStore }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-pgbouncer-stats
spec:
  # How often the Keeper API is hit
  refreshInterval: 24h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: keeper
  target:
    name: {{ .Release.Name }}-pgbouncer-stats # Name of the k8s Secret to be created
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        connection: "postgresql://postgres:{{ .password }}@127.0.0.1:6543/pgbouncer?sslmode=disable"
        username: postgres
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.secrets.dbPasswordSecretName }}
        property: password
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: {{ .Values.secrets.k8sSecretStore }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-valkey
spec:
  # How often the Keeper API is hit
  refreshInterval: 24h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: keeper
  target:
    name: {{ .Release.Name }}-valkey # Name of the k8s Secret to be created
    creationPolicy: Owner
    template:
      mergePolicy: Merge
      engineVersion: v2
      data:
        connection: "rediss://:{{ .password }}@{{ .valkey_host }}:6379/0?ssl_cert_reqs=none"
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.secrets.valkeyPasswordSecretName }}
        property: password
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: {{ .Values.secrets.k8sSecretStore }}
    - secretKey: valkey_host
      remoteRef:
        key: ack-outputs
        property: {{ .Release.Namespace }}.{{ .Release.Name }}-valkey-host
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: {{ .Values.secrets.k8sSecretStore }}
