dags:
  repo: ~
  branch: ~
envName: ~
clusterName: ~
dnsName: ~
ackOutputsNamespace: ~
secrets:
  k8sSecretStore: ~
  valkeyPasswordSecretName: airflow-valkey-creds
  dbPasswordSecretName: airflow-db-creds
  adminPasswordSecretName: airflow-admin-login
  githubAppSecretName: ~
  githubAppPrivateKeySecretKey: ~
  githubAppInstallIdSecretKey: ~
  githubAppClientIdSecretKey: ~
  connectionsSecretName: airflow-connections
helm:
  timeout: 30m
  interval: 30m
  install:
    retries: 1
  upgrade:
    retries: 1
airflow:
  image:
    repository: ~
    digest: ~
    tag: ~
  env:
    - name: AWS_REGION
      value: us-east-1
  celery:
    replicas: 2
    resources: {}
    terminationGracePeriodSeconds: 2700
    concurrency: 2
    nodeSelectorExtra: ~
    env: []
  apiServer:
    replicas: 2
    resources: {}
  scheduler:
    replicas: 1
    resources: {}
  triggerer:
    replicas: 1
    resources: {}
  dagProcessor:
    replicas: 1
    resources: {}
pgbouncer:
  replicas: 1
  resources: {}
aws:
  adoptAckResources: false
  accountId: ~
  kmsKeyId: ~
  kmsKeyArn: ~
  kmsPolicyArn: ~
  elasticache:
    securityGroupID: ~
    cacheSubnetGroupName: ~
    engineVersion: "9.0"
    automaticFailoverEnabled: false
    multiAZEnabled: false
    numNodeGroups: 1
    replicasPerNodeGroup: 0
  clusterOIDCArn: ~
  clusterOIDCUrl: ~
  s3:
    autoExpireFiles: false
    lifetime: 7
  rds:
    engineVersion: ~
    maxAllocatedStorage: 40
    multiAZ: false
    securityGroupID: ~
    dbSubnetGroupName: ~
    deletionProtection: false
    backupRetentionPeriod: 0
