dagGitBranch: main
envName: ~
clusterName: ~
aws:
  kmsKeyId: ~
  kmsPolicyArn: ~
  elasticacheSgId: ~
  elasticacheSubnetGroup: ~
  clusterOIDCArn: ~
  clusterOIDCUrl: ~
  rdsVersion: ~
  rdsSubnetGroup: ~
  rdsSgId: ~
  rdsBackupRetentionPeriod: 0
