---
# Object store (backup) config
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: {{ include "cnpg-cluster.fullname" . }}
  labels:
    {{- include "cnpg-cluster.labels" . | nindent 4 }}
spec:
  # By default, just map the whole values.objectStore onto here
  {{- toYaml .Values.objectStore | nindent 2 }}
