---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: {{ include "citygeo-cnpg-cluster.fullname" . }}
spec:
  # By default, just map the whole values.scheduledBackup onto here
  {{- toYaml .Values.scheduledBackup | nindent 2 }}
  # Forced config
  cluster:
    name: {{ include "citygeo-cnpg-cluster.fullname" . }}
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
